import { Component, OnInit } from '@angular/core';
import { FormBuilder, FormGroup, Validators } from '@angular/forms';
import { Router } from '@angular/router';
import { PayrollService } from '../../../services/payroll.service';
import { PayrollModel } from '../../../models/payroll.model';

@Component({
  selector: 'app-createpayroll',
  templateUrl: './createpayroll.component.html',
  styleUrls: ['./createpayroll.component.css'],
})
export class CreatePayrollComponent implements OnInit {
  payrollForm: FormGroup;
  loading = false;
  errorMessage: string | null = null;

  constructor(
    private fb: FormBuilder,
    private payrollService: PayrollService,
    private router: Router
  ) {
    this.payrollForm = this.fb.group({
      employeeId: ['', Validators.required],
      managerId: ['', Validators.required],
      hourlyRate: [0, Validators.required],
      performanceBonuses: [0, Validators.required],
      insurance: [0, Validators.required],
      medicare: [0, Validators.required],
      deductions: [0, Validators.required],
      overtimeHours: [0, Validators.required],
      overtimeRate: [0, Validators.required],
      yearlySickDay: [0, Validators.required],
      payDate: ['', Validators.required],
    });
  }

  ngOnInit(): void {}

  onSubmit(): void {
    if (this.payrollForm.valid) {
      this.loading = true;
      const payroll: PayrollModel = new PayrollModel(
        '', // Payroll ID will be generated by the server
        this.payrollForm.value.employeeId,
        this.payrollForm.value.managerId,
        this.payrollForm.value.hourlyRate,
        this.payrollForm.value.performanceBonuses,
        this.payrollForm.value.medicare,
        this.payrollForm.value.deductions,
        this.payrollForm.value.overtimeHours,
        this.payrollForm.value.overtimeRate,
        this.payrollForm.value.yearlySickDay,
        new Date(this.payrollForm.value.payDate)
      );

      this.payrollService.createPayroll(payroll).subscribe(
        () => {
          this.loading = false;
          this.router.navigate(['/payrolls/list']);
        },
        (error) => {
          this.errorMessage = 'Failed to create payroll.';
          this.loading = false;
          console.error('Failed to create payroll', error);
        }
      );
    }
  }

  resetForm(): void {
    this.payrollForm.reset();
  }

  cancel(): void {
    this.router.navigate(['/payrolls/list']);
  }
}
